# Make sure color works
set -as terminal-features "xterm*:RGB"
setenv -g COLORTERM 'truecolor'

set -s set-clipboard on

# Define new prefix
set -g prefix C-j

# Prefer vi for scrollback
set-window-option -g mode-keys vi
set -g history-limit 10000

# vi pane switching
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Change colors
set -g status-style 'fg=white bg=blue'
set -g window-status-current-style 'fg=black bg=cyan'
