# Make sure color works
set -as terminal-features "xterm*:RGB"
set -as terminal-features "foot:clipboard:RGB"
setenv -g COLORTERM 'truecolor'

set -s set-clipboard on
set -g allow-passthrough on

# Define new prefix
set -g prefix C-s

# Prefer vi for scrollback
set-window-option -g mode-keys vi
set -g history-limit 10000

# add a resize mode with prefix + r
bind-key r switch-client -T resizemode
bind-key -T resizemode h resize-pane -L 2 \; switch-client -T resizemode
bind-key -T resizemode j resize-pane -D 2 \; switch-client -T resizemode
bind-key -T resizemode k resize-pane -U 2 \; switch-client -T resizemode
bind-key -T resizemode l resize-pane -R 2 \; switch-client -T resizemode
bind-key -T resizemode Enter switch-client -T root
bind-key -T resizemode Escape switch-client -T root

# Change colors
set -g status-style 'fg=#ffffff bg=#285577'
set -g window-status-current-style 'fg=black bg=cyan'

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.config/tmux/plugins/tpm/tpm'
